prev: Předchozí
next: Další
comment: Komentáře
share: Sdílet
powered_by: Powered by
rss_feed: RSS Feed
no_title: (bez titulku)
recent_posts: Česky třeba?
newer: Novější
older: Starší
Articles: Články
